In [7]:
import pandas as pd
import numpy as np

In [8]:
test = pd.read_csv('test.csv')
test_ID = test['Id']

In [13]:
data = pd.read_csv('kaggle_submission_fin.csv')
data = np.array(data['SalePrice'])
data

array([121762.65329505, 166351.7054316 , 184252.9799629 , ...,
       168158.09169944, 116414.08947988, 219036.61895475])

In [14]:
dat = pd.read_csv('kaggle_submission_fin (1).csv')
dat = np.array(dat['SalePrice'])
dat

array([121762.65329505, 166351.7054316 , 184252.9799629 , ...,
       168158.09169944, 116414.08947988, 219036.61895475])

In [15]:
svm = pd.read_csv('kaggle_submission_fin (2).csv')
svm = np.array(svm['SalePrice'])
svm

array([121762.65329505, 166351.7054316 , 184252.9799629 , ...,
       168158.09169944, 116414.08947988, 219036.61895475])

In [12]:
Id = test_ID
fin_score = pd.DataFrame({'SalePrice': (svm/3 + dat/3 + data/3)}) # adding the final weight due to score
fin_data = pd.concat([Id,fin_score],axis=1)
fin_data.to_csv('another_submission.csv',index=False) # to submission
fin_data.head(20)

Id      SalePrice
0   1461  121762.653295
1   1462  166351.705432
2   1463  184252.979963
3   1464  194806.746750
4   1465  190962.829068
5   1466  172905.688429
6   1467  178244.600883
7   1468  163373.545832
8   1469  190318.774978
9   1470  124351.230125
10  1471  190070.528627
11  1472   97126.239958
12  1473   96548.121873
13  1474  142468.678331
14  1475  111501.595429
15  1476  368752.131808
16  1477  255437.127440
17  1478  286353.057838
18  1479  283069.523728
19  1480  550258.838330